
delete   from dbo.CommandeReceptionDetail
delete   from dbo.CommandeReception
truncate table dbo.LibelleSpecialArticleFournisseur
truncate table dbo.LiaisonArticleFournisseur
delete   from  dbo.AGAC
truncate table AppelOffreArticleDetailArticleCommande
truncate table dbo.CommandeArticle
delete from    dbo.TypeArticleCommande
truncate table dbo.DemandeStock
truncate table dbo.AppelOffreArticleDetailArticleParPoste
truncate table dbo.AppelOffreArticleDetailPoste
delete from   dbo.AppelOffreArticle
delete  from dbo.CommandeParArticle
truncate table dbo.Avoir
 truncate table dbo.FactureFournisseurEtranger
truncate table dbo.FactureFournisseurMaroc
truncate table dbo.FactureFRET
delete from dbo.TypeAvoir
delete from dbo.TypeFacture
truncate table dbo.CompositionArticle
delete from dbo.TypeComposition
delete from  dbo.NatureEngin
truncate table dbo.Prevision
delete from dbo.TypePrevision
truncate table dbo.Comptabilite
truncate table dbo.ArticleParMagasinProjet
truncate table dbo.ArticleParMagasin
truncate table dbo.ArticleParProjet
delete from  dbo.TypeInventaire

delete from  dbo.TypeMagasin
delete from articleparmagasin
delete from magasin
delete from dbo.AppelOffreParArticleProjet
delete from  dbo.AppelOffreParArticle
delete from dbo.Situation
truncate table dbo.AccessoireCommandeDetail
delete from  dbo.AccessoireCommande
delete from  dbo.AppelOffre
delete from dbo.RestructionAO
delete from dbo.typeAppelOffre
delete from dbo.Projet
delete from dbo.DirectionProjet
delete from dbo.Reapprovisionnement
delete from dbo.Commande
delete from dbo.TypeCommande
delete from  dbo.ModePaiement
delete from  dbo.Urgence
delete from   dbo.MarocainEtranger
delete from  dbo.CaracteristiqueCommande
delete from   dbo.Article
delete from dbo.MethodeReapprovisionnement
delete from  dbo.TypeAchat
delete from  dbo.MatiereArticle
delete from  dbo.CaracteristiqueArticle
delete from  dbo.Etablissement
delete from  dbo.Fournisseur
delete from  dbo.ModeConfection
delete from   dbo.OrigineArticle
delete from  dbo.Origine
delete from  dbo.NonApprovisionnement
delete from  dbo.Direction
delete from  dbo.ClassementArticle
delete from  dbo.FamilleArticle
delete from dbo.LibelleArticle
delete   FROM ReferenceArticle
delete from typeparc

